/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
 * Generated on: 17-Nov-2023 13:02:38
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 58
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s30,30 -> [-5.000000e-01 5.000000e-01)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
// #include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020a\extern\include\tmwtypes.h 
 */
const int BL = 58;
const int16_T B[58] = {
     -232,    -47,    109,    319,    462,    430,    205,   -104,   -314,
     -278,     -1,    343,    504,    323,   -133,   -580,   -681,   -285,
      426,    990,    938,    132,  -1056,  -1847,  -1447,    478,   3523,
     6642,   8610,   8610,   6642,   3523,    478,  -1447,  -1847,  -1056,
      132,    938,    990,    426,   -285,   -681,   -580,   -133,    323,
      504,    343,     -1,   -278,   -314,   -104,    205,    430,    462,
      319,    109,    -47,   -232
};
